const crypto = require("crypto");
const util = require("util");
const pbkdf2Async = util.promisify(crypto.pbkdf2);

// Django's PBKDF2 stored format:
//   pbkdf2_sha256$<iterations>$<salt>$<base64(dk)>
//
// Salt in Django's PBKDF2 is a random ASCII string (alphanumeric) generated by
// BasePasswordHasher.salt(). It's not base64-encoded in the stored format.
function parseDjangoPBKDF2(encoded) {
  const parts = String(encoded).split("$", 4);
  if (parts.length !== 4) return null;

  const [algorithm, iterationsStr, salt, hash] = parts;
  const iterations = Number(iterationsStr);
  if (!algorithm.startsWith("pbkdf2_")) return null;
  if (!Number.isFinite(iterations) || iterations <= 0) return null;

  const digest = algorithm.replace("pbkdf2_", "");
  return { algorithm, iterations, salt, hash, digest };
}

function constantTimeEqualString(a, b) {
  const ab = Buffer.from(String(a));
  const bb = Buffer.from(String(b));
  if (ab.length !== bb.length) return false;
  return crypto.timingSafeEqual(ab, bb);
}

async function pbkdf2Hash({ plain, salt, iterations, digest }) {
  const keyLen = digest === "sha1" ? 20 : digest === "sha256" ? 32 : 0;
  if (!keyLen) {
    throw new Error(`Unsupported digest: ${digest}`);
  }

  const derivedKey = await pbkdf2Async(
    String(plain),
    String(salt),
    iterations,
    keyLen,
    digest
  );
  return derivedKey.toString("base64");
}

async function verifyDjangoPassword(plainPassword, encodedPassword) {
  const parsed = parseDjangoPBKDF2(encodedPassword);
  if (!parsed) return false;

  const computed = await pbkdf2Hash({
    plain: plainPassword,
    salt: parsed.salt,
    iterations: parsed.iterations,
    digest: parsed.digest,
  });

  return constantTimeEqualString(computed, parsed.hash);
}

function makeSaltFromSaltLength(saltLength) {
  const alphabet =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const bytes = crypto.randomBytes(saltLength);
  let out = "";
  for (let i = 0; i < saltLength; i++) {
    out += alphabet[bytes[i] % alphabet.length];
  }
  return out;
}

async function hashDjangoPassword(plainPassword, { iterations, digest, saltLength }) {
  const algorithm = `pbkdf2_${digest}`;
  const salt = makeSaltFromSaltLength(saltLength);
  const hash = await pbkdf2Hash({
    plain: plainPassword,
    salt,
    iterations,
    digest,
  });

  return `${algorithm}$${iterations}$${salt}$${hash}`;
}

module.exports = {
  parseDjangoPBKDF2,
  verifyDjangoPassword,
  hashDjangoPassword,
};
